# Prometheus Configuration for AI Council System
# Collects metrics from application, containers, and system resources

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    cluster: 'ai-council-production'
    environment: 'production'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # Add alertmanager targets here if needed
          # - alertmanager:9093

# Rule files for alerts
rule_files:
  # - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # AI Council application metrics
  - job_name: 'ai-council'
    static_configs:
      - targets: ['ai-council:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'python_.*'
        action: keep

  # Debate-specific metrics
  - job_name: 'debates'
    static_configs:
      - targets: ['ai-council:8080']
    metrics_path: '/metrics/debates'
    scrape_interval: 30s

  # Streaming metrics
  - job_name: 'streaming'
    static_configs:
      - targets: ['ai-council:8080']
    metrics_path: '/metrics/streaming'
    scrape_interval: 10s

  # PostgreSQL metrics (requires postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187']
    scrape_interval: 30s

  # Redis metrics (requires redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']
    scrape_interval: 30s

  # Nginx metrics (requires nginx-prometheus-exporter)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 30s

  # Container metrics (cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Node/system metrics (node_exporter)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'node_.*'
        action: keep

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 60s
